import "./globals.css";
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import NextUiProvider from "@/Provider/NextUiProvider";
import Container from "@/components/Container";
import Side from "@/components/Side";
import Player from "@/components/Player";
import SupabaseProvider from "@/Provider/SupabaseProvider";
import UserProvider from "@/Provider/UserProvider";
import ModalProvider from "@/Provider/ModalProvider";
import ToastProvider from "@/Provider/ToastProvider";

export const metadata: Metadata = {
  title: "Spotify-Clone",
  description: "Generated by create next app",
};

const font = Figtree({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${font.className} dark text-foreground bg-background w-full h-[100vh] fixed`}
      >
        <NextUiProvider>
          <SupabaseProvider>
            <UserProvider>
              <ModalProvider />
              <ToastProvider />
              <Container>
                <Side />
                {children}
              </Container>
              <Player />
            </UserProvider>
          </SupabaseProvider>
        </NextUiProvider>
      </body>
    </html>
  );
}
